### ISSUE TITLE
Feedback for project binding by Wenny

### ISSUE THREAD

**Issue by wennychao** [sarahsaroufim/binding#1]
Hello Sarah! it's nice to see you again! Here are some feedback base on your html and css file!
First of all, it's amazing to see how much effeort you have put into this project! The code is super organized and easy to read. You have utilized the variables well here as well as the grid! Also, I can see you have a strong theme for the reading selections in the landing page. The letters are acting like single elements in its own shape, super clever! I see you are working on scaling the letters proportionally. However, just to keep in mind, it might be a long scroll for reader to reach the reading at the bottom of the page! Maybe you can add a hover states to the letters to trigger some interaction with the reader. 
For example:
```
a {
    font-size: 1em;}
a:hover {
    font-size: 3em;}

```
/*----------------*/

It's just an idea! you can play with it an see how it works with your design.

Also, I realized some texts are in default setting. I search up the font that you are using and it looks like it's in Arabic. I am not sure if it's my browser not reading the font. 
```
#home-description{
    font-family: var(--font-lyon-slanted);}
#coming-soon{
    font-family: var(--font-lyon-slanted);}
```

Overall, the design looks great and is eye catching! especially the little smiley face in the footer :) super cute. I am excited to see your final design! keep up and good luck! 

By Wenny

**Comment by sarahsaroufim** [comment]
thank you queen
